<?php
/**
 * This file prints the CSS code generated by the customizer inside the header tag.
 * @author vcatalin007@gmail.com
 */

// Get the saved font transient.
$fontTransient = get_transient("book_rev_lite_gfonts_transient");

// Decode the transient
$fontTransient = json_decode($fontTransient);

// Fonts available to select by user.
$fontsUsed = array(
	'article-title-font',
	'article-content-font',
	'meta-info-font'
);

book_rev_lite_build_font_url($fontsUsed, $fontTransient);


echo "<style type='text/css'>";

// If book_rev_lite Product Review plugin is active and running set up the special classes.
include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
if(is_plugin_active('wp-product-review/wp-product-review.php')) {
	$setColors = book_rev_lite_get_product_review_colors();
	foreach($setColors as $key => $value) echo ".grade." . $key . " { background: " . $value . " !important;} ";
}


// Set lower footer background color.
$book_rev_lite_wpc_upper_footer_bg_color = get_theme_mod("lower-footer-background-color");
if($book_rev_lite_wpc_upper_footer_bg_color != '')
	{
		echo "#main-footer .lower-footer { background:" .  $book_rev_lite_wpc_upper_footer_bg_color . "; }";
	}

// Set upper footer background color.
$book_rev_lite_wpc_footer_bg_color = get_theme_mod("footer-background-color");
if($book_rev_lite_wpc_footer_bg_color != '')
	{
		echo "#main-footer .upper-footer { background:" .  $book_rev_lite_wpc_footer_bg_color . "; }";
	}

// Set header background color.
$book_rev_lite_wpc_header_bg_color = get_theme_mod("header-background-color");
if($book_rev_lite_wpc_header_bg_color != '')
	{
		echo "#inner-header { background:" .  $book_rev_lite_wpc_header_bg_color . "; }";
	}

// Set header menu background color.
$book_rev_lite_wpc_header_menu_bg_color = get_theme_mod("header-menu-background-color");
if($book_rev_lite_wpc_header_menu_bg_color != '')
	{
		echo "#main-menu { background:" .  $book_rev_lite_wpc_header_menu_bg_color . "; }";
	}

// Set header logo.
$book_rev_lite_wpc_header_logo = get_theme_mod("header-logo");
$book_rev_lite_wpc_header_logo_width = get_theme_mod("logo-width");
$book_rev_lite_wpc_header_logo_height = get_theme_mod("logo-height");

if($book_rev_lite_wpc_header_logo != '')
	{
		echo "#inner-header .logo { background:url('" .  $book_rev_lite_wpc_header_logo . "') no-repeat; width: " . $book_rev_lite_wpc_header_logo_width . "px !important; height: " . $book_rev_lite_wpc_header_logo_height . "px !important;}";
	}

// Set the main page layout styles.
$book_rev_lite_wpc_layout_style = get_theme_mod("mp_layout_type");
if($book_rev_lite_wpc_layout_style == "sidebarleft")
	{
		echo ".article-container { margin-right: 0; margin-left: 1.4%; }";
	}
elseif ($book_rev_lite_wpc_layout_style == "fullwidth")
	{
		echo ".article-container { margin: 0; width: 100%; }";
	}

// Set the featured category block background color.
$book_rev_lite_featured_categ_block_bg_color = get_theme_mod("featured-category-block-bgcolor");
if($book_rev_lite_featured_categ_block_bg_color != "")
	{
		echo ".featured-carousel { background:" . $book_rev_lite_featured_categ_block_bg_color . ";}";
	}

// Set the latest articles block background color.
$book_rev_lite_la_block_bgcolor = get_theme_mod("latest-articles-block-bgcolor");
if($book_rev_lite_la_block_bgcolor != "")
	{
		echo "#latest-reviews-block .lrb-inner { background:" . $book_rev_lite_la_block_bgcolor . ";}";
		echo "#latest-reviews-block .article-display .article-text { background: " . $book_rev_lite_la_block_bgcolor . ";}";
	}

// Set the latest articles item hover background color.
$book_rev_lite_lab_item_bgcolor = get_theme_mod("lab-article-hover-bgcolor");
if($book_rev_lite_lab_item_bgcolor != "")
	{
		echo "#latest-reviews-block .article-link.active, #latest-reviews-block .article-link:hover { background:" . $book_rev_lite_lab_item_bgcolor . " !important; }";
	}

// Set the highlight of the Day block background color.
$book_rev_lite_hotd_block_bgcolor = get_theme_mod("hotd-bg-color");
if($book_rev_lite_hotd_block_bgcolor != "")
{
	echo "#highlight-day .highlight-inner { background:".$book_rev_lite_hotd_block_bgcolor.";}";
}

// Set the article background color.
$book_rev_lite_article_bgcolor = get_theme_mod("article-bgcolor");
if($book_rev_lite_article_bgcolor)
{
	echo ".article-container article { background:".$book_rev_lite_article_bgcolor." ;}";
}

// Set the pagination background color.
$book_rev_lite_pagination_bgcolor = get_theme_mod("pagination-bgcolor");
if($book_rev_lite_pagination_bgcolor != "")
{
	echo "nav#pagination { background: " . $book_rev_lite_pagination_bgcolor . " ;}";
}

// Block Header Background color.
$book_rev_lite_blockheader_bgcolor = get_theme_mod("block-header-bgcolor");
if($book_rev_lite_blockheader_bgcolor != "")
{
	echo ".article-container .newsblock > header { background:" . $book_rev_lite_blockheader_bgcolor . ";}";
}

// Widget Header Background Color.
$book_rev_lite_widget_header_bgcolor = get_theme_mod("widget-header-bgcolor");
if($book_rev_lite_widget_header_bgcolor != "")
{
	echo "#main-sidebar .widget header { background:" . $book_rev_lite_widget_header_bgcolor . ";}";
}

// Widget Header Top Border Color.
$book_rev_lite_widget_header_border_bgcolor = get_theme_mod("widget-header-border-color");
if($book_rev_lite_widget_header_border_bgcolor != "")
{
	echo "#main-sidebar .widget header { border-color:" . $book_rev_lite_widget_header_border_bgcolor . ";}";
}

// Pagination Button Color.
$book_rev_lite_pagination_button_color = get_theme_mod("pagination-button-color");
if($book_rev_lite_pagination_button_color != "")
{
	echo "nav#pagination ul li a { background:" . $book_rev_lite_pagination_button_color . ";}";
}

// Pagination Button Color Hover
$book_rev_lite_pagination_button_color = get_theme_mod("pagination-button-color-hover");
if($book_rev_lite_pagination_button_color != "")
{
	echo "nav#pagination ul li a:hover { background:" . $book_rev_lite_pagination_button_color . ";}";
}

// Pagination Button Color Active
$book_rev_lite_pagination_button_active = get_theme_mod("pagination-button-color-active");
if($book_rev_lite_pagination_button_active != "")
{
	echo "nav#pagination ul li.active a { background:" . $book_rev_lite_pagination_button_active . ";}";
}

// Articles Title Fonts
$book_rev_lite_article_title_font = get_theme_mod("article-title-font");
if($book_rev_lite_article_title_font !== "")
{
	echo "
		article a.title, .article-title a, .title a, .sd-title a, .featured-carousel .slide .article-content header h3,
		.article-container.post > header .title,
		.article-container.post #wrap-up .review-header h3,
		#main-menu nav ul li a,
		#top-bar-menu ul li a,
		.widget header h2
		{ font-family: " . '"' .  $fontTransient->items[$book_rev_lite_article_title_font]->family . '"' . ", sans-serif !important; }
	";
}

// Articles Content Font
$book_rev_lite_article_content_font = get_theme_mod('article-content-font');
if($book_rev_lite_article_content_font !== "") {
	echo "
		#slider .slide .sd-body p,
		.featured-carousel .slide .article-content .content p,
		#latest-reviews-block .article-display .article-text,
		.widget.latest-comments p,
		#highlight-day p,
		.widget.text p,
		.article-container article p,
		#main-footer .widget .comment,
		#main-footer .widget .article,
		.textwidget,
		.widget,
		.widget a,
		.review-body .option-name,
		.article-container.post #wrap-up .proscons li
		{ font-family: " . '"' .  $fontTransient->items[$book_rev_lite_article_content_font]->family . '"' . ", sans-serif !important; }
	";
}

$book_rev_lite_meta_info_font = get_theme_mod('meta-info-font');

if($book_rev_lite_meta_info_font !== "") {
	echo "
		.featured-carousel .slide .article-content header .meta .category a,
		.featured-carousel .slide .article-content header .meta .date,
		#slider .sd-meta .read-more,
		#slider .sd-meta span a,
		#latest-reviews-block .article-link .article-meta .categ a,
		#latest-reviews-block .article-link .article-meta .date,
		#latest-reviews-block .article-display .a-details .category a,
		#latest-reviews-block .article-display .a-details .date,
		.widget.topbooks .meta .categ a,
		.widget.topbooks .meta .date,
		.featured-carousel .slide .feat-img .comment-count a,
		.article-container article .feat-img .comment-count a,
		#latest-reviews-block .article-display .featured-image .a-meta .grade,
		#latest-reviews-block .article-display .featured-image .a-meta .no-comments a,
		.widget.topbooks .grade,
		.widget.latest-comments h4,
		#highlight-day .meta .categ a,
		#highlight-day .meta .date,
		.article-container article header .meta .categ a,
		.article-container article header .meta .date,
		.widget.topbooks .meta .categ a,
		.widget.topbooks .meta .date,
		.widget.topbooks .grade,
		.featured-carousel .slide .feat-img .grade,
		.article-container article .feat-img .grade,
		#slider .slide .slide-description .top-sd-head .grade,
		#slider .sd-meta span,
		.article-container.post > header .article-details .date
		{ font-family: " . '"' .  $fontTransient->items[$book_rev_lite_meta_info_font]->family . '"' . ", sans-serif !important; }
	";
}


echo "</style>";
